Food Delivery Time Prediction


-Goal: given the details of an order — who is delivering it, how far it has to travel, the weather, 
the traffic, the time of day, and so on — predict how many minutes the delivery will take.

-This is a supervised regression problem. The target, Time_taken(min), is a continuous number, 
and we have thousands of labelled historical orders to learn from.

Roadmap

Load & inspect the raw data  
Clean the messy text and missing values  
EDA — find which features actually move delivery time  
Feature engineering — turn raw lat/long and timestamps into useful signals (distance, hour of day)  
Encode & scale the features  
Train and compare four models — Linear Regression → Decision Tree → Random Forest → XGBoost  
Tune, evaluate, and save the best model for inference

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r'D:\ML-Projects\food-delivery\Food-Delivery-Time-Prediction\Food delivery.csv')

In [6]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [7]:
df.shape

(45593, 20)

In [8]:
# Dtypes + null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  str
 3   Delivery_person_Ratings      45593 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  str
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  str
dtypes: float64(4), int64(1), str(15)
memory usage: 11.9 MB

In [9]:
# Values may be stored as strings even when they look numeric — check the actual type
type(df['Delivery_person_Age'][0])

str

In [10]:
# Note the messy formatting: categories arrive as "conditions Sunny", plus a literal "conditions NaN"
df['Weatherconditions'].value_counts()

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

In [13]:
df[df['Weatherconditions']=='conditions NaN']

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
74,0xa9f,BANGRES13DEL01,NaN,NaN,12.935662,77.614130,12.975662,77.654130,11-03-2022,NaN,15:30:00,conditions NaN,NaN,1,Drinks,scooter,0,No,Metropolitian,(min) 19
120,0x6e2,VADRES06DEL01,NaN,NaN,22.312790,73.170283,22.422790,73.280283,02-04-2022,NaN,18:25:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,(min) 25
250,0x1b50,PUNERES16DEL01,NaN,NaN,18.536718,73.830327,18.646718,73.940327,08-03-2022,NaN,21:25:00,conditions NaN,NaN,3,Buffet,motorcycle,1,Yes,Urban,(min) 43
348,0x4c1,BANGRES13DEL02,NaN,NaN,12.935662,77.614130,13.065662,77.744130,02-03-2022,NaN,00:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 26
425,0xc003,DEHRES13DEL02,NaN,NaN,-30.366322,-78.070453,30.496322,78.200453,18-02-2022,NaN,22:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,(min) 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45332,0x2950,VADRES04DEL02,50,6,0.000000,0.000000,0.020000,0.020000,19-03-2022,NaN,10:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,(min) 28
45394,0xdc4,RANCHIRES02DEL03,NaN,NaN,0.000000,0.000000,0.030000,0.030000,05-03-2022,NaN,17:25:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,(min) 21
45504,0x461,BANGRES07DEL02,NaN,NaN,-12.978453,-77.643685,12.998453,77.663685,17-03-2022,NaN,09:30:00,conditions NaN,NaN,3,Meal,scooter,1,No,NaN,(min) 24
45518,0x863,INDORES05DEL01,NaN,NaN,22.727021,75.884167,22.737021,75.894167,19-03-2022,NaN,11:40:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,(min) 25
45519,0xd0be,AGRRES07DEL01,NaN,NaN,27.160934,78.044095,27.170934,78.054095,13-02-2022,NaN,09:05:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Urban,(min) 17

Basic Data Cleaning

Fix free-text formatting quirks (e.g. "conditions Sunny" → "Sunny").  
Replace the literal string 'NaN' with a real, pandas-recognized null.  
Strip stray whitespace from every text column.  
Convert numeric-looking text columns to actual numbers.  
Impute missing values (median for skewed numerics, mode for categoricals).

In [14]:
df['Weatherconditions']

0             conditions Sunny
1            conditions Stormy
2        conditions Sandstorms
3             conditions Sunny
4            conditions Cloudy
                 ...
45588         conditions Windy
45589         conditions Windy
45590        conditions Cloudy
45591        conditions Cloudy
45592           conditions Fog
Name: Weatherconditions, Length: 45593, dtype: str

In [15]:
# Test the parsing idea on one value before applying it to the whole column
temp = 'conditions Sunny'

In [18]:
# Keep the word after the space; leave real nulls untouched
temp.split(" ")[1] if pd.notnull(temp) else temp

'Sunny'

In [25]:
df['Weatherconditions'] = df['Weatherconditions'].apply(lambda temp : temp.split(" ")[-1] if pd.notnull(temp) else temp)

In [26]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='str')

In [27]:
df.select_dtypes(include='object').columns

C:\Users\Mohd Shamsher\AppData\Local\Temp\ipykernel_18344\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Type_of_order', 'Type_of_vehicle', 'multiple_deliveries', 'Festival',
       'City', 'Time_taken(min)'],
      dtype='str')

In [28]:
# For every text column: remove leading/trailing spaces, and turn the literal
# string 'NaN' (not a real null) into an actual np.nan so pandas treats it as missing
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()
    df[col] = df[col].replace('NaN', np.nan)

C:\Users\Mohd Shamsher\AppData\Local\Temp\ipykernel_18344\2863888055.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [29]:
df[df['Weatherconditions']=='conditions NaN']

Empty DataFrame
Columns: [ID, Delivery_person_ID, Delivery_person_Age, Delivery_person_Ratings, Restaurant_latitude, Restaurant_longitude, Delivery_location_latitude, Delivery_location_longitude, Order_Date, Time_Orderd, Time_Order_picked, Weatherconditions, Road_traffic_density, Vehicle_condition, Type_of_order, Type_of_vehicle, multiple_deliveries, Festival, City, Time_taken(min)]
Index: []

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  str
 3   Delivery_person_Ratings      43685 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  str
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  str
dtypes: float64(4), int64(1), str(15)
memory usage: 11.2 MB

The target column is dirty too. Time_taken(min) is stored as text like "(min) 24" instead of the number 24. A model can only regress on numbers, so we split off the label and cast it to int, while carefully leaving genuine missing values as NaN instead of crashing on them.

In [32]:
# Target column still stored as text, e.g. "(min) 24"
type(df['Time_taken(min)'][0])

str

In [33]:
# Same one-value test for the target's "(min) 24" format
temp = '(min) 24'

In [36]:
int(temp.split(' ')[1] )if pd.notnull(temp) else temp

24

In [38]:
# Target cleanup: "(min) 24" -> 24 (int). Keep real NaNs as NaN instead of crashing on them
df['Time_taken(min)'] = df['Time_taken(min)'].apply(lambda temp : int(temp.split(" ")[1]) if pd.notnull(temp) else temp)

In [39]:
type(df['Time_taken(min)'][0])

numpy.int64

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  str
 3   Delivery_person_Ratings      43685 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  str
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(4), int64(2), str(14)
memory usage: 10.9 MB

In [41]:
# Looks numeric but may be stored as text — worth confirming before we cast
df['multiple_deliveries'].value_counts()

multiple_deliveries
1    28159
0    14095
2     1985
3      361
Name: count, dtype: int64

Cast the numeric-looking columns to real numbers. errors='coerce' is the key detail: anything that still cannot be parsed becomes NaN rather than raising an exception, which lets us impute those gaps in a single clean step later on.

In [42]:
# Force genuinely numeric columns to numeric dtype; errors='coerce' turns any
# leftover bad values into NaN instead of raising, so we can impute them next
for col in ['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries']:
    df[col] = pd.to_numeric(df[col] , errors='coerce')

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  float64
 3   Delivery_person_Ratings      43685 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  float64
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.6 MB

In [44]:
# Summary stats — a quick way to spot impossible values (e.g. a rating > 5)
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken(min)
count,43739.000000,43685.000000,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000,44600.000000,45593.000000
mean,29.567137,4.633780,17.017729,70.231332,17.465186,70.845702,1.023359,0.744664,26.294607
std,5.815155,0.334716,8.185109,22.883647,7.335122,21.118812,0.839065,0.572473,9.383806
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.546947,75.898497,18.633934,76.002574,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,2.000000,1.000000,32.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000,54.000000

In [49]:
df[df['Delivery_person_Ratings']>5]['Delivery_person_Ratings']

3586     6.0
4714     6.0
5169     6.0
5362     6.0
5651     6.0
6394     6.0
7031     6.0
7681     6.0
9499     6.0
9535     6.0
10100    6.0
10737    6.0
12297    6.0
13257    6.0
13652    6.0
14106    6.0
14907    6.0
14944    6.0
16798    6.0
17145    6.0
17708    6.0
18977    6.0
19382    6.0
20269    6.0
21320    6.0
22416    6.0
23375    6.0
24237    6.0
24918    6.0
25285    6.0
26052    6.0
27221    6.0
27399    6.0
28315    6.0
28974    6.0
29535    6.0
30579    6.0
30943    6.0
31233    6.0
32326    6.0
33533    6.0
34688    6.0
38007    6.0
38020    6.0
38561    6.0
38649    6.0
39699    6.0
40223    6.0
41105    6.0
41969    6.0
42072    6.0
42835    6.0
45332    6.0
Name: Delivery_person_Ratings, dtype: float64

In [52]:
df['Delivery_person_Ratings']=df['Delivery_person_Ratings'].clip(upper=5)
df['Delivery_person_Ratings']

0        4.9
1        4.5
2        4.4
3        4.7
4        4.6
        ...
45588    4.8
45589    4.6
45590    4.9
45591    4.7
45592    4.9
Name: Delivery_person_Ratings, Length: 45593, dtype: float64

In [53]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken(min)
count,43739.000000,43685.000000,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000,44600.000000,45593.000000
mean,29.567137,4.632567,17.017729,70.231332,17.465186,70.845702,1.023359,0.744664,26.294607
std,5.815155,0.331560,8.185109,22.883647,7.335122,21.118812,0.839065,0.572473,9.383806
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.546947,75.898497,18.633934,76.002574,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,2.000000,1.000000,32.000000
max,50.000000,5.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000,54.000000

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  float64
 3   Delivery_person_Ratings      43685 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  float64
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.6 MB

In [57]:
# The mode = most frequent category; this is the value we'll use to impute missing categoricals
df['Road_traffic_density'].mode()[0]

'Low'

Imputing the remaining missing values


Two column types need two different strategies:


Numeric columns → fill with the median. The median is robust to outliers and skew, so a few extreme values will not drag the fill value around the way the mean would.
Categorical columns → fill with the mode (the most frequent category), which is the only sensible "average" for a non-numeric field.

In [58]:
# Numeric columns: fill missing values with the median (robust to outliers/skew)
for col in ['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries']:
    df[col] = df[col].fillna(df[col].median())

In [59]:
# Categorical columns: fill missing values with the mode (most frequent category)
for col in ['Weatherconditions','Road_traffic_density','Festival','City']:
    df[col] = df[col].fillna(df[col].mode()[0])

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  float64
 3   Delivery_person_Ratings      45593 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  float64
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.6 MB